services:
  - type: web
    name: telegram-music-bot
    env: docker
    repo: https://github.com/akggautamasar/telmusic
    branch: main
    envVars:
      - key: BOT_TOKEN
        value: your_bot_token_here
